---
- name: Install prerequisites
  apt: name={{ item }} update_cache=yes state=present
  with_items:
    - build-essential
    - python-apt
    - python-pycurl
    - apt-transport-https
  become: yes
  become_user: root

- name: Add the Nodesource apt key
  shell: wget -qO - https://deb.nodesource.com/gpgkey/nodesource.gpg.key | sudo apt-key add -
  become: yes
  become_user: root

# We previously added node v4 repo so now we'll have to clean it up
- name: Remove outdated Nodesource repository (v4)
  apt_repository: >
    repo='{{ item }} {{ ansible_distribution_release }} main'
    state=absent
    update_cache=yes
  with_items:
    - 'deb https://deb.nodesource.com/node_4.x'
    - 'deb-src https://deb.nodesource.com/node_4.x'
  become: yes
  become_user: root

- name: Add Nodesource repository for v6
  apt_repository: >
    repo='{{ item }} {{ ansible_distribution_release }} main'
    state=present
    update_cache=yes
  with_items:
    - 'deb https://deb.nodesource.com/node_6.x'
    - 'deb-src https://deb.nodesource.com/node_6.x'
  become: yes
  become_user: root

- name: Install Node.js
  apt: name=nodejs update_cache=yes state=latest
  become: yes
  become_user: root
