ansible_user: "ansible"
ansible_group: "ansible"
rollback_to: ""

_update_apt_cache: yes
_node_version: 8.11.3
_deploy_to: "/CPDB/CPDBv2_mobile"
_releases: "{{ _deploy_to }}/releases"
_current: "{{ _deploy_to }}/current"
_logs: "{{ _deploy_to }}/logs"

nvm:
  user: "{{ ansible_user }}"
  version: v0.33.11
  node_version: "{{ _node_version}}"
  yarn_version: 1.7.0

nginx:
  update_apt_cache: "{{ _update_apt_cache }}"
  template: "nginx"
  app_path: "{{ _current }}"
  configuration_name: cpdb-mobile
  access_log: "{{ _logs }}/access_log"
  error_log: "{{ _logs }}/error_log"
  server_name: ms.cpdp.co
  enable_https: no

deploy:
  user: "{{ ansible_user }}"
  group: "{{ ansible_group }}"

  deploy_to: "{{ _deploy_to }}"
  releases: "{{ _releases }}"
  logs: "{{ _logs }}"
  current: "{{ _current }}"
  temp: "/tmp/mobilev2-build-"

  node_version: "{{ _node_version}}"

  webpack_env: "staging"
  branch: staging
  git_repo: git@github.com:EastAgile/CPDBv2_mobile.git
  keep_releases: 30

rollback:
  releases: "{{ _releases }}"
  rollback_to: "{{ rollback_to }}"
  current: "{{ _current }}"
