version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.11.3-browsers

    steps:
      - checkout
      - run: sudo npm install i -g yarn@1.7.0
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Install Dependencies
          command: yarn install

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run: yarn run lint
      - run: yarn run ci-test
      - run: yarn run live-test
  deploy:
    docker:
      - image: circleci/python:3.6.4

    steps:
      - checkout
      - run: pipenv install
      - run: pipenv run ansible-playbook -i ansible/staging ansible/deploy.yml

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: staging
