version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.11.3-browsers

    steps:
      - checkout
      - run: sudo npm install i -g yarn@1.7.0
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - /home/circleci/.cache/yarn/v1

      - run: yarn run lint
      - run: yarn run ci-test
      - run: yarn run live-test
  deploy:
    docker:
      - image: circleci/node:8.11.3-browsers

    steps:
      - checkout
      - run: sudo npm install i -g yarn@1.7.0
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Build assets
          command: |
            if [ $CIRCLE_BRANCH == "master" ]
            then
              export AZURE_STORAGE_ACCOUNT_NAME=$AZURE_STORAGE_PROD_ACCOUNT_NAME
            else
              export AZURE_STORAGE_ACCOUNT_NAME=$AZURE_STORAGE_STAGING_ACCOUNT_NAME
              export WEBPACK_ENV=staging
            fi && \
            yarn dist
      - run:
          name: Copy static files to azure storage
          command: ./bin/copy-to-azure-storage.js

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - staging
                - master
