---


- name: Get number of releases
  shell: echo `ls -1t {{ rollback.releases }} | wc -l`
  register: rollback_versions

- name: Check if there is more than one release
  fail:
    msg: "Could not roll back the code because there is no prior releasE"
  when: rollback_versions.stdout|int <= 1

- name: Get current release version
  shell: echo `ls -1t {{ rollback.releases }} | head -n 1`
  register: rollback_current_release

- stat:
    path: "{{ rollback.releases }}/{{ rollback.rollback_to }}"
  register: stat_rollback_release_version
  when: rollback.rollback_to != ""

- name: Check that the provided rollback release exists
  fail:
    msg: "Specified rollback version does not exist"
  when: rollback.rollback_to != "" and (stat_rollback_release_version.stat.exists is not defined or stat_rollback_release_version.stat.isdir == False)

- name: Get previous releases version
  shell: echo `ls -1t {{ rollback.releases }} | head -n 2 | tail -n 1`
  register: previous_release_version

- name: Get rollback release version
  set_fact:
    rollback_release_version: "{{ rollback.rollback_to if rollback.rollback_to != '' else previous_release_version.stdout }}"

- name:  Change symlink from current release to {{ rollback_release_version }}
  file:
    state: link
    path: "{{ rollback.current }}"
    src: "{{ rollback.releases }}/{{ rollback_release_version }}"
