---

- name: Ensure deployment base path exists
  file:
    state: directory
    path: "{{ deploy.deploy_to }}"
    owner: "{{ deploy.user }}"
    group: "{{ deploy.group }}"
    recurse: yes
  become: yes

- name: Ensure releases folder exists
  file:
    state: directory
    path: "{{ deploy.releases }}"


- name: Ensure logs folder exists
  file:
    state: directory
    path: "{{ deploy.logs }}"
