---
- name: Creates CPDB directory for deployment
  become: yes
  become_user: root
  file: path=/CPDB state=directory owner={{ deploy_user }} group={{ deploy_group }}
  tags: setup

- name: Pull code from frontend repo
  git: repo=git@github.com:EastAgile/CPDBv2_mobile.git
    dest={{ application_root_path }}
    accept_hostkey=True
    version={{ branch }}
    force=yes
    key_file=/home/{{ deploy_user }}/.ssh/khoi_github
  when: pull_code_from_git
  tags: deploy

- name : Install packages based on package.json.
  command: yarn install
    chdir={{ application_root_path }}
  tags: deploy

- name: Make sure `/var/www` is available
  file: path=/var/www state=directory owner={{ deploy_user }} group={{ deploy_group }}
  become: yes
  become_user: root
  tags: deploy

- name: Make sure logs directory is available
  file: path={{ application_logs_path }} state=directory owner={{ deploy_user }} group={{ deploy_group }} mode=0774
  tags: deploy

- name: Clean old build
  file: path={{ application_dist_path }}/dist state=absent
  tags: deploy

- name: Build everything
  command: yarn run {{ yarn_command }}
    chdir={{ application_root_path }}
  register: build_dist
  tags: deploy

- name: find index.html
  stat:
    path={{ application_root_path }}/dist/index.html
  register: index_exists
  tags: deploy

- debug: msg="{{ build_dist.stdout_lines }}"
  when: index_exists.stat.exists == False
  tags: deploy

- fail:
    msg: "Whoops! the build was not success, the index.html doesn't exist"
  when: index_exists.stat.exists == False
  tags: deploy

- name: Clean static root
  become: yes
  become_user: root
  file: path={{ nginx_dist_path }} state=absent
  tags: deploy

- name: Clean old nginx dist build
  file: path={{ nginx_dist_path }} state=absent
  tags: deploy

- name: Move file to dist
  command: mv {{ application_dist_path }}/dist {{ nginx_dist_path }}
  tags: deploy
